---
- hosts: docker_node
  become: yes
  roles:
    - name: docker
      tags: ['docker']

  post_tasks:
    - name: Disable systemd-resolved service
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
      tags: ['always']

    - name: Set nameserver to localhost
      copy:
        content: "nameserver {{ loadbalancer_ip }}"
        dest: /etc/resolv.conf
        mode: 0644
      tags: ['always']

    - name: Restart Docker to pick up DNS change
      systemd:
        name: docker
        state: restarted
      tags: ['docker']
